print("opa , vai corithians!")
print('Etou vendo o jogo!')
print("Vou juntar", "o texto")
print("Vou"+"concatenar"+"o texto")
print("5 + 5")
print("5" + "5")
print("5","5")
print(5 + 5)
print("O resultado de 5+5 é:", 5+5)
print("O resultado de 5+5 é:", 5+5, "!")
print("")